### ISSUE TITLE
Scenarios not compatible with next

### ISSUE THREAD

**Issue by mwola** [robohydra/robohydra#19]
When calling one method let's say /services/ i'm using 
 req.url = req.url.concat("login");
 next(req, res);

It should return lets say /services/login. It is working. When i turn on scenario and type /services/login - scenario is returned. But When i use /services and next it doesn't return active scenario - it returns normal response from plugin.

**Comment by emanchado** [comment]
Hm, I cannot think of any reason why that wouldn't work just because the head is part of a scenario. Are you sure that the reason isn't that the /services/ head is *below* the scenario heads? You can go to http://localhost:3000/robohydra-admin/ and see the head order (after you have activated the scenario, of course).

If that's indeed the case, you'll have to register your /services/ head dynamically with the "registerDynamicHead" method in the RoboHydra object. See the [logger plugin](https://github.com/robohydra/robohydra/blob/master/plugins/logger/index.js) source code for an example.

I'll close this for now, assuming my theory is right. Please reopen if I was wrong!

**Comment by mwola** [comment]
Thanks for quick reply. Indeed using registerDynamicHead solved issue.
