### ISSUE TITLE
Feature: Option to use rawHeaders from request (rather than lowercased headers)

### ISSUE THREAD

**Issue by cuongluu8** [robohydra/robohydra#26]
Yes, HTTP Headers are meant to be case-insensitive, so node automatically lowercasing all header keys should be OK.
However in some cases where a backend service doesn't fully adhere to the W3C recommendation and insists on HTTP headers being case sensitive, then if I using Robohydra to proxy to this service then it will not work since the HTTP headers will be lowercased.
I would like to propose a change to allow you to use the `rawHeaders` from the Request object rather than the `headers`.  This can be controlled by a new config property e.g. `useRawHeaders = true`.
I would be happy to do the change and raise a PR for this.

**Comment by emanchado** [comment]
Wow, are there web servers broken like that?

I'm a bit worried about exposing the raw headers because if you make the request object use them, you will most likely break some plugins (I could try to fix the standard plugins, but I'm sure I'll forget to add support for that for newer plugins, and any plugins written by RoboHydra users could break, too). And if you make both available, it will be a mess when you try to update some header, because the other kind won't be updated and they will be inconsistent.

Do you have any ideas about how to tackle this? I wonder if the solution could be completely different, like write your own proxying function that converts the headers back to their "standard" casing.

**Comment by cuongluu8** [comment]
Using the rawHeader instead of the lowercase headers shouldn't break anything going forward - after all they're supposed to be case sensitive right? The key/value should be the same.
The change I was going to propose was in the `robohydraserver.js` in the `makeRequestHandler`.
Something like this
```
nodeReq.addListener("end", function () {
        var req = new Request({
            url: nodeReq.url,
            method: nodeReq.method,
            headers: config.useRawHeaders ? buildHeadersFromRaw(nodeReq.rawHeaders) : nodeReq.headers,
            rawBody: reqBody
        });
        summoner.summonRoboHydraForRequest(req).handle(req, res);
});
```

**Comment by emanchado** [comment]
I mean if you have code that checks or modifies headers, like [this code](https://github.com/robohydra/robohydra/blob/master/lib/heads.js#L519) in `RoboHydraHeadFilter`:

    if (res.headers['content-length'] !== undefined) {
        res.headers['content-length'] = res.body.length;
    }

If the header is really `Content-Length`, the condition will be true, and a second header will be added (regardless of the contents of the actual `Content-Length`, if any.

**Comment by cuongluu8** [comment]
correct me if I'm wrong - but by the time the request has reached the `*Head` the request headers will have already been lower-cased by node?

**Comment by emanchado** [comment]
Maybe I'm misunderstanding what you want or what the problem is :-) I didn't even know about rawHeaders so maybe I'm missing something.

I thought your idea was to pass the headers verbatim through RoboHydra, so that when it reached some `RoboHydraHeadProxy`, it would pass around the initial, verbatim headers without lowercasing. If that's the case, what I mean is that there could be a `RoboHydraHeadFilter` before the proxy head, checking and/or modifying headers.

If you say that the headers will have been lowercased by Node by the time they reach RoboHydra heads, what difference would it make? Don't you need the original headers in a `RoboHydraHeadProxy`, so it passes them around to another server?

**Comment by cuongluu8** [comment]
What I'm doing is using robohydra to proxy all incoming request through to another server (like any normal http proxy server) using the `RoboHydraHeadProxy` (I then use scenarios to mimic specific endpoints being unavailable).
However when the request reaches the server all headers have been lowercased (by node) and therefore the serve rejects the request with a 500 response.
Node are adamant that lowercasing all request headers is correct, but they are including `rawHeaders` in the request (for people like me 😄 ).
So in `robohydraserver` it will get the `nodeRequest` object and convert it to a local (robohydra) `Request`.  It is this process that I'm proposing to change, so when it creates this local robohydra Request there will be an option to use the `rawHeaders` from the nodeReq rather than `headers`.
These `headers` will be the forwarded to the end server via the `RoboHydraHeadProxy` preserving it's original case.

**Comment by emanchado** [comment]
Hm, let's see. When a request comes, RoboHydra creates a RoboHydra `Request` object from it. At this point is when your change would happen.

Then, the list of heads is searched for one matching the incoming request. The list of heads could have a `RoboHydraHeadFilter` first (which would trigger a bug), then a `RoboHydraHeadProxy` that receives the (possibly broken) request object and would send it to your server.

That's why I was saying that, as the problem seems to be that server, maybe it would make sense to make the change in what talks to it? Surely that server expect every bit in the header name to be capitalised: in that case, it should be an easy change. Or actually that makes me think, shouldn't the HTTP request functions in Node already "fix" header names so they look like what most people expect?

**Comment by cuongluu8** [comment]
How does it perform the matching of the incoming request?   Do you have the code in question for me to inspect?
How does having `RoboHydraHeadFilter` first cause a bug?

Some people think that node lowercasing the headers is a little heavy handed - If I post a request with headers = {MyCamelCasedHeader : 'Value'}, then I would expected to receive this header on the server as `{MyCamelCasedHeader : 'Value'}` rather than `{mycamelcasedheader: 'Value'}'.

I don't have the option of making the services accept case-insensitive, so need an alternative solution.

**Comment by cuongluu8** [comment]
I raised https://github.com/robohydra/robohydra/pull/27 that might better explain what I am trying to achieve.
I tested it for my needs and it seems to work OK.
I would still need to write tests around this as well

**Comment by emanchado** [comment]
Thanks! It's probably easier to be able to try things and point at code. Also, my filter example was silly because `RoboHydraHeadFilter` is for responses, not requests, but the point still applies.

OK, with the code you have there, create a plugin and a configuration file with the content in https://gist.github.com/emanchado/099c851f98b41480b005d68e29237ca9. Now, make a request and note how, when setting `useRawHeaders`, the `If-Modified-Since` header is still there. That's a bug, because the `no-caching` plugin tries to remove the `if-modified-since` header, if it's there. Setting `useRawHeaders` to false makes the header disappear (but of course they will all be lowercase).

Header names are usually in the form of `Words-Separated-By-Dashes`, so it shouldn't be hard to change them to those right before proxying from RoboHydra. Or do you have headers that don't follow that pattern, like `CamelCase-Inside`?

**Comment by cuongluu8** [comment]
The `If-Modified-Since` bug can be easier fix in a number of ways I think - thanks for pointing that out (I can fix that on my forked version). e.g. you could look iterate over all headers to look for this header in a case sensitive way.  
Might be a safer way anyway as you're making the assumption that the header is always lower-case rather than case-sensitive.  Node could end up upper-casing all it's headers rather than lowercasing.

I have no control over the format of the headers required by the services - which is the point of having this change really.  I know some headers are like `Account-ID`

**Comment by emanchado** [comment]
Ugh, `Account-ID`. Yikes.

About the `If-Modified-Since` bug, the point is that many other, very subtle bugs can and will appear both in standard plugins and with whatever plugins other people might write, so I really don't think that changing the `no-caching` plugin to support the `useRawHeaders` option is the way to go.

Headers *are* case-insensitive in HTTP, and Node's convention is to lowercase them (it's clearly documented so I consider that part of the API). If they changed that I'm pretty sure they would break dozens, maybe hundreds of Node projects. So that's not an issue.

I do want to try to find a solution, but I don't want to change basic assumptions about headers that can break code, especially since that would go not only against the current assumptions in RoboHydra, but in Node.js itself.

Sadly, the best idea I've had so far is to create a new head right before your proxy head, that will modify the headers to make them have the case your server expects. Because not all headers are capitalised in a regular way, you will have to make exceptions, either for known headers like `Account-ID`, or for words like `ID`. It sucks, but it's a pretty special case (and arguably a bug in the server you're contacting) so from that point of view it's not completely terrible either. You can probably get away with something like this (haven't tested it, though, but the idea comes across):
```javascript
new RoboHydraHead({
    name: 'header-case-fixer',
    path: '/.*',
    handler: function(req, res, next) {
        var newHeaders = {};

        Object.keys(req.headers).forEach(function(headerName) {
            var words = headerName.split("-");
            var newHeaderName = words.map(function(word) {
                return word === "id" ?
                    "ID" :
                    word[0].toUpperCase() + word.slice(1);
            }).join("-");

            newHeaders[newHeaderName] = req.headers[headerName];
        });

        req.headers = newHeaders;
        next(req, res);
    }
})
```

**Comment by cuongluu8** [comment]
I completely understand where you're coming from now. 
Your suggestion could work for me and it means no forked version which is always good so going to give that a go.

**Comment by emanchado** [comment]
Excellent :-) Please tell me if it works for you, so I can close this and the pull request. Or feel free to close yourself once you confirm that fixes your problem.

Thanks!

**Comment by cuongluu8** [comment]
Works a charm - much appreciated for your help on this

**Comment by emanchado** [comment]
Glad we found a solution :-)
