### ISSUE TITLE
http://localhost:3000/robohydra-admin return 404

### ISSUE THREAD

**Issue by Hydrock** [robohydra/robohydra#33]
npm i robohydra
npm run robohydra -n
RoboHydra ready on port 3000 - Admin URL: http://localhost:3000/robohydra-admin
server back 404

**Comment by emanchado** [comment]
Weird, I cannot reproduce :-/ Is there something weird in your network configuration, maybe?

Does it return 404 in `/robohydra-admin` or in `/`? Because the second would be expected... Also, does it otherwise work well when you load plugins and such? It's not clear to me if it's the first time you try RoboHydra or if you had used it before and think there's a regression in the latest version...

**Comment by emanchado** [comment]
Wow, that's... surprising :-/ Can you try with `robohydra -n -P logger` and have a look at the resulting `robohydra.log`? It almost seems like it isn't RoboHydra that is producing that response.

Also, do you have some browser extension that shows eg. 404 pages in a special way? Because by default it should give a very simple response, no JSON or anything like that. Can you show the "Response" tab in the `/robohydra-admin` response in developer tools?

Also, what happens if you make a GET request to `/robohydra-admin/rest/plugins`?

**Comment by Hydrock** [comment]
I apologize. Some infection hung on the 3000 port

**Comment by emanchado** [comment]
Wait a second, that sounds weird. If the port is busy I wouldn't be able to start RoboHydra in the first place (that happens to me sometimes, I know it works)!

Must be something subtler than that.

**Comment by Hydrock** [comment]
this port is occupied by a docker. Maybe something special))
