### ISSUE TITLE
RoboHydraHeadProxy appending null onto paths for node v9 and above

### ISSUE THREAD

**Issue by KingScooty** [robohydra/robohydra#34]
I've got a simple RoboHydraHeadProxy setup:

```js
new RoboHydraHeadProxy({
	name: 'Proxying any request into the webapp on port 3003',
	mountPath: '/',
	proxyTo: 'http://localhost:3003'
})
```

Using node v8 this works as expected. 
I can hit `localhost:3123`, and the request is properly proxy'd to `localhost:3003`

However, if i upgrade to any major node version after this (v9+), all my requests are 404ing.

A request to :
`localhost:3123` is now going to `localhost:3003/null`
`localhost:3123/page1` is now going to `localhost:3003/page1null`

It seems to be something within RoboHydra that isn't working well with node v9+.

**Comment by emanchado** [comment]
Ah, it seems that `url.search` returns `null` (instead of `""`) in Node >= 9.

I have a tentative fix on the branch [`issue34-proxy-broken-on-node9`](https://github.com/robohydra/robohydra/tree/issue34-proxy-broken-on-node9). Can you give it a try and confirm that it's fixed for you, too? I'll do more testing on my side, fix some other issue I just noticed, and push and release when you confirm that everything is good.

**Comment by KingScooty** [comment]
Hi @emanchado sorry for the slow response! Just tried this branch in the office this morning, and that's fixed the issue! 👍 

Thanks so much for the quick response! It's really appreciated!

**Comment by emanchado** [comment]
Nice. I'll close, then. I don't have time today for proper testing + a release, but I'll merge the fix to `master` and will close this.

Thanks for the report and the fix confirmation!

**Comment by KingScooty** [comment]
Sounds good! I'll keep a look out for the release! 

Cheers!
